### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-set#21]
- [ ] Document `set.Translate`. Probably shouldn't be called with `new`.
- [ ] Fix strange links:

<img width="581" alt="canjs_can-set__utilities_for_comparing_sets" src="https://cloud.githubusercontent.com/assets/78602/14365437/4cbe9ad4-fcd3-11e5-9197-5bdccb82534e.png">

**Comment by pYr0x** [comment]
please also document the sort comparator
