### ISSUE TITLE
What's the proper way to handle `$limit`?

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-set#26]
Results were getting removed from my lists every time an attribute was updated because the object's didn't have a `$limit` attribute.  I was able to get it to work properly by doing the following:

``` js
let algebra = new Set.Algebra(
  Set.comparators.sort("$sort"),
  {
    $limit: function(){
      return true;
    }
  }
);
```

Is there a better way to handle it?

**Comment by marshallswain** [comment]
@justinbmeyer answered here https://github.com/canjs/can-set/pull/25#issuecomment-234805142

**Comment by justinbmeyer** [comment]
now the answer is http://canjs.github.io/canjs/doc/can-set.props.offsetLimit.html
