### ISSUE TITLE
Is it possible to assign logic to certain properties by default?

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-set#27]
MongoDB has unique syntax for `$sort` and `$limit` among others.  Is there a way we can wire this up so I don't have to manually define the algebra in each of my models?

``` js
let algebra = new Set.Algebra(
  Set.comparators.sort("$sort"),
  {
    $limit(){
      return true;
    }
  }
);
```

Maybe this should be a can-connect issue?

**Comment by justinbmeyer** [comment]
@marshallswain what do you mean by "wire this up"?

Yes, you can create your own comparators like those in http://canjs.github.io/canjs/doc/can-set.props.html.  It should even be possible to create a comparator for multiple so you could create an algebra like:

let algebra = new set.Algebra( mongoAlgebra(), set.props.boolean("completed") )

**Comment by justinbmeyer** [comment]
closing b/c this seems like a question.
